### ISSUE TITLE
Create `CytoImageList` object in the app

### ISSUE THREAD

**Issue by ynanli** [BodenmillerGroup/cytoviewer#17]
Great work! I cannot imagine how people in the lab would love this app. <br>
Is it possible to add the feature of creating `CytoImageList` objects in the app? So that the `image`, `mask`, and `object` can be loaded by selecting folders in the app.

**Comment by lassedochreden** [comment]
Hi @ynanli, thanks a lot for the note and in principle good idea! 

At this point, we encourage users to use the `cytomapper::loadImages` function separately to create `CytoImageList` objects, because there are some manual steps required to match information between the `image`, `mask` and `object` data (See **point 4.2/4.3/4.4** at https://www.bioconductor.org/packages/release/bioc/vignettes/cytomapper/inst/doc/cytomapper.html#4_Reading_in_data) and the in-memory representation will in turn also allow the use of all functionality from `cytomapper` and `cytoviewer`. 

Will close this for now, but feel free to re-open to discuss further.
